### PR TITLE
Update ThunderBadgeQuest.lua

### PR DESCRIPTION
**Pull request by Rympex**

### CODE REVIEW

**Comment by ghost** [comment]
Could you add Picking up "Old Rod" in this quest?
It just needs to talk to NPC "Fisherman Guru Earl" on cell (0, 6) in "Fisherman House - Vermilion" of "Vermilion City".

Also, maybe add the condition to buy the bicycle ticket if you have the 75k.
Details are talking to NPC "Samuel" on cell (8, 6) in "VermilionHouse2Bottom" of "Vermilion City", then going back to "Cerulean City Bike Shop" in "Cerulean City" to talk to NPC "Bike Salesman" on cell (12, 7), he's behind a counter so cell of character would be (10,7).

I think this would make the rest much easier if we update the script to move in bicycle when outside if one has bicycle item.

**Comment by Rympex** [comment]
Add old rod is ok, but use money for get bike is only waste of money, is not necessary bike for bot, and for exp in seafoam u need more money, i will add good rod too on fuchisia

**Comment by ghost** [comment]
Well, I understand what you mean, but IF the player wants to buy it, maybe add a boolean in config,lua to buy it or not (set `false` as default), it adds the option for the bot to move faster in training and needing PC, or just moving to other cities or routes; efficiency is always nice :wink: 

In my case, for Seafoam I ended up with more money than what I started.

**Comment by Rympex** [comment]
I will push the new Edits in less,
- Added Old Rod on SaffronGuardQuest.lua
- Added get "Bike Voucher" if variable is set on true on SaffronGuardQuest and if Money > 75000
- Added Good Rod if have Old Rod and money > 15000 on  ToCinnabarQuest.lua

**Comment by ghost** [comment]
I see you made it all! Thanks for reconsidering and for all your work, you are amazing!

**Pull request closed without merging**
