### PR TITLE
New Quest: RocketCeladonQuest

### PR DESCRIPTION
**Pull request by Rympex**
Quest for solve Rocket Team on Celadon City and get Eevee

Tested 6 Times and work

### CODE REVIEW

**Comment by ghost** [comment]
There's an issue here.
On Route 7 for training to level 30, the bot goes back to pokecenter for healing after only winning 1 battle.

**Comment by Rympex** [comment]
Team Level? try explain all conditions or i can't help u, i don't get this issue, and tested like 7 8 times
or use Discord Chat:  Proshine Channel --> @Rympe

**Comment by ghost** [comment]
Ok, all my team are below level 30, so it goes to route 7 to train, but after winning 1 battle, it goes back to pokecenter for healing and then comes back to train on route 7, it wins 1 battle and goes back to pokecenter again, it's a loop.

**Comment by Rympex** [comment]
Are u using version QuestingLua0,20b ?

**Comment by ghost** [comment]
Yes I am.
The condition `not game.isTeamFullyHealed()` in Route 7 is making the bot walk back to pokecenter after a battle because I receive some damage after every single battle.

**Comment by Rympex** [comment]
Removed, my version of gamelib.lua and quest.lua, was different, i removed it on Route7 now is only NeedPokecenter, let me know if is ok

**Comment by ghost** [comment]
It's working better now, it only goes back to pokecenter when it needs it :smiley: 
Edit: tested and worked; tho the teamlevel had to go 4 more levels.

**Comment by Skyvus** [comment]
Bot keeps going on a loop saying "Rocket Team is Over" after its done , i've also place my RainbowBadgeQuest inside my QuestManager below "RocketCeladonQuest" please check ;) 

Thanks in advance !

**Pull request closed without merging**
