### PR TITLE
TempFix: forget the most inefficient move

### PR DESCRIPTION
**Pull request by Rympex**
is only a temporary fix for get in team only pokemon with damage move

tested and work:

[11:37:36] Mankey has grown to level 28.
[11:37:36] You found 28 Pokedollar(s). 
[11:37:36] You have won the battle. 
[11:37:38] [Learning Move: Rage --> Forget Move: leer]

### CODE REVIEW

**Comment by ghost** [comment]
Quite interesting, one question tho, what does `TP` stand for? whats does it mean?

**Comment by Rympex** [comment]
TP is TotalPower, or better TotalDamage

Example Tackle TP = ((35 x 50) / 1) = 1750
35 = Move Max PP
50 = Move Power
1 = Accuracy% / 100

**Comment by ghost** [comment]
Ah, I get it now, it returns the approximated total amount of damage performed by a move.
Interesting parameter, thank you so much for the quick reply ;)

**Comment by ghost** [comment]
The formula isn't considering moves like "Aerial Ace" which returns an accuracy of `-1`, but it has an "always hit" property regardless of accuracy reduction from the user or opponent's evasion.

**Comment by Rympex** [comment]
is only a temporary fix, till TeamManager Class

u can add manually the MoveName near

`if MoveName == nil or MoveName == "cut" or MoveName == "surf" or MoveName == "flash" or MoveName == "Aerial Ace" then
`

**Comment by ghost** [comment]
I think the formula is calculating TP the wrong way, it gets higher with lower accuracy values.
It should be `((Power x MaxPP)*(Accuracy/100))`

**Comment by Rympex** [comment]
Edited, was this the original idea

**Pull request closed without merging**
